# build Java CI with Gradle

on:
    push:
      # ignore *.md *.yml file changes
        branches: [ '*' ]
        paths-ignore:
          - '**.md'
          - '**.yml'
    pull_request:
        branches: [ '*' ]

permissions:
    contents: read

# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Caches Gradle packages
            uses: actions/cache@v3
            with:
              path: |
                  ~/.gradle/caches
                  ~/.gradle/wrapper
              key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
              restore-keys: |
                  ${{ runner.os }}-gradle-
          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
                java-version: '17'
                distribution: 'temurin'
          - name: Grant execute permission for gradlew
            run: chmod +x ./gradlew
          - name: Build with Gradle
            run: ./gradlew build --stacktrace --no-daemon
          - name: Upload build artifact
            uses: actions/upload-artifact@v3.1.0
            with:
                name: Artifacts from ${{ github.sha }}
                path: build/libs